use_frameworks!

target 'AnyAnalytics_Example' do
  pod 'AnyAnalytics', :path => '../'

  target 'AnyAnalytics_Tests' do
    inherit! :search_paths
    pod 'AnyAnalytics', :path => '../'
    
  end
end
